### ISSUE TITLE
ask the experts PostUp = iptables -A FORWARD

### ISSUE THREAD

**Issue by qartex** [WeeJeWel/wg-easy#156]
how is it possible that the wiregurad wg0.conf

MTU = 1420

PostUp = iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1240
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostUp = iptables -A FORWARD -i eth0 -o wg0 -p tcp --syn --dport 44158 -m conntrack --ctstate NEW -j ACCEPT
PostUp = iptables -A FORWARD -i eth0 -o wg0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
PostUp = iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 44158 -j DNAT --to-destination 10.0.1.2

PostDown = iptables -D FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1240
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i eth0 -o wg0 -p tcp --syn --dport 44158 -m conntrack --ctstate NEW -j ACCEPT
PostDown = iptables -D FORWARD -i eth0 -o wg0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
PostDown = iptables -t nat -D PREROUTING -i eth0 -p tcp --dport 44158 -j DNAT --to-destination 10.0.1.2

without it being gone after every restart? 

Thanks an merry christmas

**Comment by WeeJeWel** [comment]
I've added `WG_POST_UP` and `WG_POST_DOWN` environment variables, and deployed them to release 5. Can you test if this works for you?

**Comment by qartex** [comment]
Big thanks I test it later I am in the office

**Comment by RhanCandia** [comment]
> I've added `WG_POST_UP` and `WG_POST_DOWN` environment variables, and deployed them to release 5. Can you test if this works for you?

I tried to use WG_POST_UP and WG_POST_DOWN.
I have the post-up.txt and the post-down.txt in the wireguard folder.

But after running docker-compose up -d the post-up.txt's contents get overwritten with just "Post Up". While post-down.txt remained untouched as it should be.

**Comment by carlox97** [comment]
@WeeJeWel 
Please, how exactly do I specify PostUp iptables?
The environment variable is `- WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt`
but what do I do with it? Doesn't that line just writes "Post Up" in post-up.txt? How do I set somehing like

`PostUp = iptables -I INPUT -p udp --dport 51820 -j ACCEPT
PostUp = iptables -I FORWARD -i ens18 -o wg0 -j ACCEPT
PostUp = iptables -I FORWARD -i wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o ens18 -j MASQUERADE`

as PostUp? I pasted it in post-up.txt but it gets overwritten

**Comment by TheFockinFury** [comment]
I'm also trying to figure this out. I've got multiple lines in my PostUp and PreDown clauses and I can't figure out the right syntax / right place to store them that doesn't result in errors when bringing the server up.

**Comment by carlox97** [comment]
> I'm also trying to figure this out. I've got multiple lines in my PostUp and PreDown clauses and I can't figure out the right syntax / right place to store them that doesn't result in errors when bringing the server up.

I managed to do it:

```
version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host public address
      - WG_HOST=your.host

      # Optional:
      # - PASSWORD=foobar123
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      - WG_POST_UP=iptables -I INPUT -p udp --dport 51820 -j ACCEPT; iptables -I FORWARD -i ens18 -o wg0 -j ACCEPT; iptables -I FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens18 -j MASQUERADE
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      - WG_POST_DOWN=iptables -D INPUT -p udp --dport 51820 -j ACCEPT; iptables -D FORWARD -i ens18 -o wg0 -j ACCEPT; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ens18 -j MASQUERADE

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ./conf:/etc/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: "host"
```

That's how WG_PRE_UP and DOWN are specified: adapt them to your needs (my interface is ens18)

Since you are in host mode you need to enable IP forwarding: 

1. `sudo nano /etc/sysctl.conf `
2. `uncomment net.ipv4.ip_forward=1`
3. add `net.ipv4.conf.all.src_valid_mark=1`  *
4. Save, close and reboot.

*This is not well documented but it's also done by [wg-quick](https://github.com/WireGuard/wireguard-tools/blob/13f4ac4cb74b5a833fa7f825ba785b1e5774e84f/src/wg-quick/linux.bash#L240C7-L240C7): wireguard's own script to bring up interfaces
