### ISSUE TITLE
Not working properly on Raspberry Pi OS 64bit

### ISSUE THREAD

**Issue by vordenken** [WeeJeWel/wg-easy#186]
I've installed this docker container on my raspberry pi 4 (64bit) - OS newly installed. 
I've added my phone and tested over LTE - I can ping the docker container IP (10.8.0.1) but nothing inside my home network (e.g. my router 192.168.1.1). So the basics are working but why can't I connect to anything outside the docker container? 
I also manually set net.ipv4.ip_forward=1 in the local config file.

Here's my docker stack file: 
`
version: '3'
services:
  app:
    image: weejewel/wg-easy
    environment:
      - PASSWORD=1234
      - WG_HOST=mydyn.dns
    ports:
      - "8080:8080/udp"
      - "51821:51821/tcp"
    volumes:
      - 'wireguard:/etc/wireguard'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  wireguard:
`

uname -a : Linux raspberrypi 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux

**Comment by vordenken** [comment]
Update:

After a lot of tinkering around I finally got it working. 
My setup is not the norm, I use docker in swarm mode to enable compose without installing it. 

Here's my working docker-compose file (for swarm!): 

```version: '3.7'
services:
  app:
    image: weejewel/wg-easy
    environment:
# Change password to the password you want to use for the webgui
      - PASSWORD=password
# Change XXXXX.XXX to your public IP/dyndns adress
      - WG_HOST=XXXXX.XXX
    networks:
      - bridge
    ports:
      - target: 51820
        published: 51820
        protocol: udp
        mode: host
      - target: 51821
        published: 51821
        protocol: tcp
        mode: host
    volumes:
      - 'wireguard:/etc/wireguard'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  wireguard:

networks:
  bridge:
   external: true
   name: bridge

**Comment by xyko0** [comment]
@vordenken can you please tell me how you created your bridge network ?
Everything until client connection works fine for me (over traefik), my client get the handshake and are connected but I can't reach anything (local hosts or internet)  :'(

**Comment by zibellon** [comment]
@vordenken 
I have the same issue... Please, can you help me ?
If I start wg-easy as docker compose up -d -> all works fine
BUT
When I use docker stack deploy -f wg-stack.yaml -> my clients can connect BUT all network NOT work

My stack file

```
version: "3.9"

services:
  wireguard:
    image: weejewel/wg-easy:7
    environment:
      - PASSWORD=MY_SECRET_PASSWORD
      - WG_HOST=213.183.61.164
      - WG_PORT=51820
      - WG_MTU=1280
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_DEFAULT_DNS=8.8.8.8, 8.8.4.4
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_ADDRESS=10.17.0.x
    volumes:
      # - /lib/modules:/lib/modules
      - wireguard-data:/etc/wireguard
    ports:
      - target: 51820
        published: 51820
        protocol: udp
        mode: host
      - target: 51821
        published: 51821
        protocol: tcp
        mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.node-name==VpnAms1
      labels:
        - "traefik.enable=false"

volumes:
  wireguard-data:
    external: true
```
