### ISSUE TITLE
Client connected but no traffic

### ISSUE THREAD

**Issue by jeanpaulrh** [WeeJeWel/wg-easy#198]
Hi, 
I'm sorry if this is a noob question, but I'm new to wireguard.
I managed to start the docker container using Portainer with non default network (10.6..0.x) and I tried to connect from my phone.
The connection is established (I had some trouble due to router misconfiguration, but now it's solved) and I see the wave in the admin interface. BUT
- the client can't go anywhere, using names or IPs
- if I try to open a console on the server and ping the client nothing happens.
- from the console on the server I can ping the internet and my home network.

I'm out of options... I tried to see if there is some debug mode to enable but I didn't find it.
Any Help?

**Comment by nikolak** [comment]
Same here. From what I can tell the ` AllowedIPs` in the config is always overwritten with the client IP - thus not allowing traffic to any other destination. I'm seeing `AllowedIPs = 10.8.0.2/32 ` in the `wg0.conf` for the client ` 10.8.0.2` for example.

**Comment by jeanpaulrh** [comment]
Just as test I tried a different container with this config file:

version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000                     #See point 1.
      - PGID=100                      #See point 1.
      - TZ=Europe/Madrid              #Should be adjusted according to your location
      - SERVERURL=your.domain.com     #See point 2.
      - SERVERPORT=51820              #To change see next post
      - PEERS=2                       #See point 2. Number of clients you want to configure
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0    #Only change if it conflicts
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - /SSD/config:/config           #See point 1.
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp               #To change see next post
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

and everything went ok.
The only big difference I see is the bind mount of the /lib/modules directory.
Does it count?

Thanks.

**Comment by MasroorATB** [comment]
I created my container using portainer. I was having the same problem. Removing 

> net.ipv4.ip_forward=1

 has since fixed it.

**Comment by Rustymage** [comment]
I can't get this to work either :/ 

`version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=URL.CO.UK

      # Optional:
      # - PASSWORD=foobar123
      - WG_PORT=51821
      - WG_DEFAULT_ADDRESS=10.6.0.x
      - WG_DEFAULT_DNS=191.168.1.17
      # - WG_MTU=1420
      - WG_ALLOWED_IPS=0.0.0.0/0, 192.168.1.0/24, ::/0
      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51821:51820/udp"
      - "51822:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1`

**Comment by ArtisanByteCrafter** [comment]
Also, let me just chime in and suggest if your external DNS is with Cloudflare, I had to disable DNS proxy on my A record to get traffic to work.

**Comment by chylex** [comment]
Same issue, `wg-easy` has no connection while `ghcr.io/linuxserver/wireguard` works just fine. I have no idea how to debug this, `wg show` shows no handshake even though the client says it's connected, and the only container logs are:
```
2022-04-16T12:23:25.052Z Server Listening on http://0.0.0.0:51821
2022-04-16T12:23:25.053Z WireGuard Loading configuration...
2022-04-16T12:23:25.054Z WireGuard Configuration loaded.
2022-04-16T12:23:25.054Z WireGuard Config saving...
2022-04-16T12:23:25.054Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
2022-04-16T12:23:25.108Z WireGuard Config syncing...
$ wg syncconf wg0 <(wg-quick strip wg0)
2022-04-16T12:23:25.126Z WireGuard Config synced.
```
One thing I noticed is that `ip addr` on the client shows `inet 10.0.20.0/24` with `wg-easy`, but with `ghcr.io/linuxserver/wireguard` it shows the actual IP `inet 10.0.20.3/32`.

**Comment by chylex** [comment]
Interesting, I copied the `wg0.conf` generated by `ghcr.io/linuxserver/wireguard` into `wg-easy`, ran `wg syncconf wg0 <(wg-quick strip wg0)` manually, and tried connecting using the old configuration, and it works. Something is going on with how `wg-easy` generates server or client configurations.

**Comment by chylex** [comment]
I still don't fully know what's going on, but here's what I found with Linux and NetworkManager:
1. It doesn't work if the client config's `[Interface]` `Address` defines a subnet, I had to remove `/24`
2. It doesn't work when AllowedIPs are set to all but 192.168.0.0/24` via [AllowedIPs calculator](https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/); this works perfectly fine on my Windows machine and Android phone, but not on Linux for some reason...
3. Importing the WG config does not set `PresharedKey` and `PersistentKeepalive` at all, you either have to disable preshared keys or fill them in manually - and then never touch the KDE NetworkManager GUI again, because it just spontaneously forgets the preshared keys anyway... absolute nightmare

I made a custom build of `wg-easy` that makes `PresharedKey` optional, and then manually edited the config to stop NetworkManager from having an aneurysm, and now it works.

**Comment by foureight84** [comment]
I'm having the same issue that the client is able to connect but no traffic.

```
version: "3.7"
services:
  wireguard:
    image: weejewel/wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=wg.placemarker.com #just a placeholder for this post
      - WG_DEFAULT_ADDRESS=10.40.0.0
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_ALLOWED_IPS=192.168.1.0/24, 10.84.0.0/24, 0.0.0.0/0
      - WG_MTU=1450
      - WG_PERSISTENT_KEEPALIVE=15
      - WG_POST_UP=iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      - WG_POST_DOWN=iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    volumes:
      - wireguard_config:/etc/wireguard
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
volumes:
  wireguard_config:
```
