### ISSUE TITLE
Not logged In Message on UI when running two instances at a time

### ISSUE THREAD

**Issue by Basti-Fantasti** [WeeJeWel/wg-easy#204]
Hi,

when I run the container twice on two different port sets I get this error when trying to add a new client.
I can log in, but as soon as I try to add a client, give a name and click ok, I get the "Not logged in" message and the changes are not saved.

I have set up two instances in two folders with two different container names.
I did this because I can not have templates for the configuration.

Using the first instance I will only connect to my company LAN,
using the second instance I will fully route my traffic through the VPN

The UI instances are sharing a session cookie which gets invalidated.
As soon as I log in the second instance, the session cookie keeps getting refreshed.
When I shut down one of the two instances, it's working again and the connect.sid cookie remains the same.

Here some screenshots showing the toggling cookies:

![wg1](https://user-images.githubusercontent.com/1663072/153487934-988b5483-d1fc-4a9c-9450-a4c05bf4adf6.png)

![wg2](https://user-images.githubusercontent.com/1663072/153487953-0e37f140-cb29-4a1c-a130-9ddff3be9dec.png)

![wg3](https://user-images.githubusercontent.com/1663072/153487965-32829506-2870-44cc-95c8-1a82fd04e347.png)

Some of the changes in my docker-compose files are these. The allowed IP ranges differ as well. In the wg-easy it's only my local lan/24 in the second one 0.0.0.0/24

**wg-easy:**

````
 - WG_PORT=51820
 image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
````

**wg-easy-full:**

````
   - WG_PORT=51822

    image: weejewel/wg-easy
    container_name: wg-easy-full
    volumes:
      - .:/etc/wireguard
    ports:
      - "51822:51822/udp"
      - "51823:51821/tcp
 ````

maybe making the name of the session cookie variable would/could help or fix this issue?

Sorry, I'm not so much into that 

Best regards
Bastian
