### ISSUE TITLE
Enable running multiple instances on a single server

### ISSUE THREAD

**Issue by 0x4c47** [WeeJeWel/wg-easy#222]
# Use Case
I have 2 types of clients: Admin clients and user clients. They are supposed to have different IP ranges, different DNS servers and different allowed IPs.

# My chosen solution
Run 2 instances of Wireguard on the same server: One for the admin clients and one for the user clients. Even easier with docker-compose: I just define two services with different variables.

# Why this currently doesn't work with wg-easy
## `network_mode: host`
I'm using host networking for all services on this host for specific reasons. The WG_PORT doesn't change the server configuration, the Wireguard server ListenPort is hard-coded to 51820 in [WireGuard.js](https://github.com/WeeJeWel/wg-easy/blob/master/src/lib/WireGuard.js). I can't have two instances running on one server both listening on the same port. One workaround would be not using host networking but unfortunately that's not an option in my case. As far as I can see the very simple solution would be replacing `ListenPort = 51820` by `ListenPort = ${WG_PORT}`. Imho that would also prevent some confusion about the WG_PORT variable as seen in several issues of this project.

## Hard-coded interface name wg0
The name of the Wireguard server interface is hard-coded to wg0. I can't have two instances running on one server with the same interface name. Solution would be having a variable, e.g. WG_INTERFACE_NAME, that controls the name of the interface created by Wireguard.

## Undocumented Web UI port variable
That's an easy one and related to the host networking issue: I couldn't find any documentation about the environment variable PORT that controls the listening port of the Web UI. I found it getting used in the source code; controlling the listening port using the environment variable works fine. Is there any reason for not documenting it?

# My workaround
I also wanted to share what I did to make it all work only through the means of Docker without cloning the repo and changing the source code there. In case anyone else wants to run it this way.

I'm building my own image on top of the wg-easy image using this Dockerfile:
```
FROM weejewel/wg-easy:latest
RUN sed -i 's/ListenPort = 51820/ListenPort = ${WG_PORT}/g' /app/lib/WireGuard.js
ARG WG_IFNAME
RUN grep -rl wg0 /app | xargs sed -i "s/wg0/$WG_IFNAME/g"
```
This implements the proposed solution for the ListenPort through the means of Docker image building and also replaces all occurrences of wg0 in the code with a custom interface/configuration name.

In docker-compose.yaml I'm modifying the build arguments to change the interface name build argument I'm using within the Dockerfile and I'm defining the undocumented Web UI port variable
```
services:
  wireguard:
    build:
      context: .
      network: host
      args:
        - WG_IFNAME=wg0custom
    environment:
      - PORT: 8080
      [...]
```

Thanks for this great project and I hope this helps anyone who also want's to run wg-easy this way and that these changes can be implemented.

**Comment by shizunge** [comment]
Related request:
Allow to specify UI listening address and port.

Use case:
Also using host network mode. I want to bind the UI to an internal network interface, e.g. 192.168.0.1 instead of listening to 0.0.0.0

**Comment by wakko222** [comment]
I'm not real familiar with docker.  When I use this first I get "WG_HOST Environment Variable Not Set."  Putting the WG_HOST=url seems to work. Then I get "Cannot find device "wg0custom1" and "wg0custom2."

**Comment by 0x4c47** [comment]
@wakko222 Sorry I didn't insert my whole configuration, only the parts that were relevant for this issue description. You still need the configuration parameters described within the README like WG_HOST
and the additional capabilities.
To apply the change of the interfaces, create create the docker-compose file, create the Dockerfile, run docker-compose build, wipe the saved configuration from your mounted volume directory (your previously added clients won't be able to connect after that sotake a backup if needed), then run the whole thing with docker-compose up.

**Comment by wakko222** [comment]
Gaining ground.  I am having an issue where on the second build sections, the sed command from the Dockerfile tries to run again. From the first run the "wg0" has been renamed to "$WG_IFNAME" and the build fails because it has already been changed.

**Comment by 0x4c47** [comment]
That's weird and shouldn't happen. Every build should be a fresh start since it's always based on the same image and no changes should persist from previous builds. Any weird volume mounts maybe? Do you have your exact Dockerfile and docker-compose file anywhere online so I can have a look at it?

**Comment by wakko222** [comment]
https://pastebin.com/y7T16Bna

**Comment by 0x4c47** [comment]
Try removing the "image: ..." line from your docker-conpose file. You're using a Dockerfile and "build:". That replaces the image and you're specifying the base image in your Dockerfile.

But I'm not sure if that's the issue.

But what could be an issue is the volume mount. Try to comment out that one as well for testing or rename the .wg-easy directories once in case those still contain older values.

**Comment by wakko222** [comment]
0x4c47
Would you be able to post your full docker-compose.yml (minus sensitive information) so that I could look at it?

**Comment by 0x4c47** [comment]
@wakko222 Sorry for the delay, here's my docker-compose.yaml. But please keep in mind that there's stuff in there that's very specific to my configuration. E.g. the POST_UP and POST_DOWN stuff which is just there because I manage all firewall rules on my own.
```
version: "3.8"
services:
  wireguard_first:
    build:
      context: wireguard
      network: host
      args:
        - WG_IFNAME=wg0first
    volumes:
      - ./wireguard/first:/etc/wireguard
    network_mode: host
    environment:
      - PASSWORD=verysecretpassword
      - PORT=12345
      - WG_HOST=vpn.example.org
      - WG_PORT=54321
      - WG_DEFAULT_ADDRESS=192.168.1.x
      - WG_DEFAULT_DNS=192.168.1.1
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_PERSISTENT_KEEPALIVE=30
      - WG_POST_UP=true
      - WG_POST_DOWN=true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
  wireguard_second:
    build:
      context: wireguard
      network: host
      args:
        - WG_IFNAME=wg0second
    volumes:
      - ./wireguard/second:/etc/wireguard
    network_mode: host
    environment:
      - PASSWORD=verysecretpassword
      - PORT=23456
      - WG_HOST=vpn.example.org
      - WG_PORT=65432
      - WG_DEFAULT_ADDRESS=192.168.2.x
      - WG_DEFAULT_DNS=192.168.2.1
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_PERSISTENT_KEEPALIVE=30
      - WG_POST_UP=true
      - WG_POST_DOWN=true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
```
