### ISSUE TITLE
wg-easy + pihole + reverse proxy (traefik)

### ISSUE THREAD

**Issue by david-plugge** [WeeJeWel/wg-easy#291]
I followed the [instructions](https://github.com/WeeJeWel/wg-easy/wiki/Using-WireGuard-Easy-with-Pi-Hole) on setting up wg-easy with pihole. That works pretty well but when i try to expose wireguard via traefik the wireguard clients dont have access to pihole anymore.

It seems like adding the `proxy` network to the wireguard service breaks the network. It may be possible to expose the ui port to the host and configure traefik to route to that specific host port, but that seems to require `network_mode: host` in the traefik stack which i want to avoid.

_docker-compose.yml_
```yml
version: '3.8'

networks:
    # traefik network
    proxy:
        external: true
    wg-easy:
        ipam:
            config:
                - subnet: 10.8.1.0/24

services:
    wireguard:
        image: weejewel/wg-easy
        container_name: wireguard
        restart: unless-stopped
        environment:
            WG_HOST: '****'
            PASSWORD: '****'
            WG_DEFAULT_DNS: 10.8.1.3
            WG_DEFAULT_ADDRESS: 10.8.0.x
            WG_ALLOWED_IPS: 10.8.0.0/24
        volumes:
            - /home/server/data/vpn/wireguard:/etc/wireguard
        ports:
            - 51820:51820/udp
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1
        networks:
            proxy:
            wg-easy:
                ipv4_address: 10.8.1.2
        labels:
            traefik.enable: 'true'
            traefik.http.routers.wireguard-ui.entrypoints: 'https'
            traefik.http.routers.wireguard-ui.rule: 'Host(`****`)'
            traefik.http.routers.wireguard-ui.service: 'wireguard-ui'
            traefik.http.services.wireguard-ui.loadbalancer.server.port: '51821'

    pihole:
        image: pihole/pihole
        container_name: pihole
        restart: unless-stopped
        environment:
            ServerIP: 10.8.1.3
            WEBPASSWORD: '****'
        volumes:
            - /home/server/data/pihole/etc-pihole/:/etc/pihole:rw
            - /home/server/data/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d:rw
        ports:
            - 127.0.0.1:53:53/tcp
            - 127.0.0.1:53:53/udp
        networks:
            wg-easy:
                ipv4_address: 10.8.1.3
```

**Comment by mj-crawl** [comment]
Using two netowrks within docker leads to two network interfaces eth0 and eth1. Propably, the routing uses the wrong network interface that is hard-coded to eth0.

Try using the WG_POST_UP environment variable with the correct interface, e.g. eth1:

```
    environment:
      - WG_POST_UP=iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth1 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
```

**Comment by david-plugge** [comment]
thank you @mj-crawl that just fixed it!

If anyone is interested, this is my working docker-compose file.
(I´m now using pihole + unbound, the setup is the same)

```yaml
version: '3.8'

networks:
    proxy:
        external: true
    wg-easy:
        ipam:
            config:
                - subnet: 10.8.1.0/24

services:
    wireguard:
        image: weejewel/wg-easy
        container_name: wireguard
        restart: unless-stopped
        environment:
            WG_HOST: '****'
            PASSWORD: '****'
            WG_DEFAULT_DNS: 10.8.1.3
            WG_DEFAULT_ADDRESS: 10.8.0.x
            WG_ALLOWED_IPS: 10.8.0.0/24,10.8.1.3
            WG_POST_UP: >
                iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth1 -j MASQUERADE;
                iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT;
                iptables -A FORWARD -i wg0 -j ACCEPT;
                iptables -A FORWARD -o wg0 -j ACCEPT;
        volumes:
            - /home/server/data/vpn/wireguard:/etc/wireguard
        ports:
            - 127.0.0.1:51821:51821/tcp
            - 51820:51820/udp
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1
        networks:
            proxy:
            wg-easy:
                ipv4_address: 10.8.1.2
        labels:
            com.centurylinklabs.watchtower.enable: 'true'
            traefik.enable: 'true'
            traefik.http.routers.wireguard-ui.entrypoints: 'https'
            traefik.http.routers.wireguard-ui.rule: 'Host(`****`)'
            traefik.http.routers.wireguard-ui.service: 'wireguard-ui'
            traefik.http.services.wireguard-ui.loadbalancer.server.port: '51821'

    pihole:
        container_name: pihole
        image: cbcrowe/pihole-unbound:latest
        restart: unless-stopped
        networks:
            wg-easy:
                ipv4_address: 10.8.1.3
        ports:
            - 127.0.0.1:53:53/tcp
            - 127.0.0.1:53:53/udp
        environment:
            ServerIP: 10.8.1.3
            TZ: Europe/Berlin
            WEBPASSWORD: '****'
            REV_SERVER: 'false'
            DNS1: 127.0.0.1#5335 # Hardcoded to our Unbound server
            DNS2: 127.0.0.1#5335 # Hardcoded to our Unbound server
            DNSSEC: 'true' # Enable DNSSEC
        volumes:
            - /home/server/data/pihole/etc-pihole/:/etc/pihole:rw
            - /home/server/data/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d:rw
        labels:
            com.centurylinklabs.watchtower.enable: 'true'
```
