### ISSUE TITLE
VueApexCharts is not defined

### ISSUE THREAD

**Issue by oooh-name** [WeeJeWel/wg-easy#315]
Script error occured when loading login page:

```
Uncaught ReferenceError: VueApexCharts is not defined
    at app.js:29:16
```

docker image: weejewel/wg-easy:7

**Comment by joshuanianji** [comment]
Did you manage to solve this? I also have this error running this with both versions 6 and 7.

I'm using the following `docker-compose.yml`:

```yml
version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${HOST}

      # Optional:
      - PASSWORD=${PASSWORD}
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      
    image: weejewel/wg-easy:7
    container_name: wg-easy
    volumes:
      - ./.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
