### ISSUE TITLE
Error on PiHole Install == 0.0.0.0:53: bind: address already in use

### ISSUE THREAD

**Issue by Lennys26** [WeeJeWel/wg-easy#347]
I am using docker-compose for the wg-easy & PiHole combined install, I am getting the following error:

```
...
Creating wg-easy ... 
Creating pihole  ... 
Creating pihole  ... error

Creating wg-easy ... donef9a2fc58b5079a27904b30a46530d6217ba43): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use

ERROR: for pihole  Cannot start service pihole: driver failed programming external connectivity on endpoint pihole (ca3425e4d0c7ff18c450c932020f9a2fc58b5079a27904b30a46530d6217ba43): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

**Below is my slightly modified yml:**
```
version: "3.8"

services:
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=111.111.111.111

      # ⚠️ Change the Web UI Password:
      - PASSWORD=<foo>

      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /root/docker/volumes/wg-easy:/etc/wireguard
    ports:
      - "51830:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2
    healthcheck:
      test: curl --fail http://localhost:51821 || exit 1
      interval: 60s
      retries: 3
      start_period: 30s
      timeout: 10s

  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      # ⚠️ Change the Web UI Password:
      - WEBPASSWORD=<bar>
    volumes:
      - '/root/docker/volumes/pihole/etc-pihole:/etc/pihole'
      - '/root/docker/volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    restart: unless-stopped
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3
    healthcheck:
      test: curl --fail http://localhost:5353 || exit 1
      interval: 60s
      retries: 3
      start_period: 30s
      timeout: 10s

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
```

### Troubleshooting so far:
* The docker host is brand new.
* `lsof -i` on the docker host shows nothing on port 53
*  `netstat -p |grep 53` on the docker host also shows nothing no port 53
