### ISSUE TITLE
how to use ipv6 for wg-easy?

### ISSUE THREAD

**Issue by Ja7ad** [WeeJeWel/wg-easy#348]
I enable ipv6 for docker and try for use ipv6 with wg-easy but not work.

```yaml
version: "3.8"
services:
  wg-easy:
    environment:
      - WG_HOST=[2a01:234:123:345::1]
      - PASSWORD=xxxx
      - WG_PORT=6001
      
    image: weejewel/wg-easy
    container_name: wireguard-vpn
    volumes:
      - ./conf:/etc/wireguard
    ports:
      - "6001:51820/udp"
      - "6001:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=0
```
