### ISSUE TITLE
Unable to access the Web UI with a fresh install

### ISSUE THREAD

**Issue by instantdreams** [WeeJeWel/wg-easy#351]
I've tried this with a minimal and extended set of Environment values, but I am unable to access the WebUI using either http://w.x.y.z:51821/ or http://servername:51821/. Here is my configuration:

My docker-compose.yml:
```
version: "3.8"
services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    hostname: ${HOSTNAME}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    environment:
      - PASSWORD=${PASSWORD}
      - WG_HOST=${WG_HOST}
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_MTU=${WG_MTU}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
    volumes:
      - ${APPDATA}:/etc/wireguard
    restart: unless-stopped
```
Initially I had PASSWORD, WG_HOST, and WG_PORT uncommented. I uncommented the last four and tried various settings in the .nv file.

My .env file:
```
# Directory locations
APPDATA=/srv/wg-easy/config/
# Container specifics
HOSTNAME=[server name]
PASSWORD=[password]
WG_HOST=[external host name]
WG_PORT=51820
WG_DEFAULT_ADDRESS=10.8.0.1
WG_DEFAULT_DNS=192.168.1.1
WG_MTU=1420
WG_ALLOWED_IPS=0.0.0.0/0
```

The 192.168.1.1 DNS is to my router.

The logs:
```
wg-easy    | 2022-08-19T18:21:40.754Z Server Listening on http://0.0.0.0:51821
wg-easy    | 2022-08-19T18:21:40.757Z WireGuard Loading configuration...
wg-easy    | 2022-08-19T18:21:40.760Z WireGuard Configuration loaded.
wg-easy    | 2022-08-19T18:21:40.761Z WireGuard Config saving...
wg-easy    | 2022-08-19T18:21:40.764Z WireGuard Config saved.
wg-easy    | $ wg-quick down wg0
wg-easy    | $ wg-quick up wg0
wg-easy    | 2022-08-19T18:21:40.944Z WireGuard Config syncing...
wg-easy    | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy    | 2022-08-19T18:21:41.002Z WireGuard Config synced.
```

Any ideas what I'm missing here?
