### ISSUE TITLE
"Cannot find device "wg0"" even though kernel supports WireGuard and wireguard-tools is installed

### ISSUE THREAD

**Issue by fischer-felix** [WeeJeWel/wg-easy#382]
**Describe the bug**
When running the command from the README on Oracle Linux 9 with podman, it fails with the message
```
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
```
However, the kernel used by OL9 (UEK R7) does support wireguard, as it is based on 5.15 LTS and I have installed `wireguard-tools` as recommended in https://github.com/WeeJeWel/wg-easy/issues/293#issuecomment-1159779565.

**To Reproduce**
1. Install podman on Oracle Linux 9
2. install `wireguard-tools` and reboot
3. run 
``` podman run \
  --name=wg-easy-test \
  -e WG_HOST=vpn.mydomain.com \
  -e PASSWORD=supersecurepassword \
  -v wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy
```

**Expected behavior**
Container starts without problems.

**Comment by fischer-felix** [comment]
So after a bit of tinkering, I got it to work!
I don't know exactly what fixed it, but I believe it was a combination of everything I did.
1. added `net.ipv4.conf.all.rp_filter=2` to the sysctls
2. added `/lib/modules:/lib/modules` to the volumes
3. ran `sudo modprobe ip_tables` on the host (as there was an error about iptables)

Here is my docker-compose file that I run using portainer on podman version 4.1.1 (Host: Oracle Cloud Instance, Oracle Linux 9)

```
version: '3'

volumes:
  data:

services:
  app:
    image: 'weejewel/wg-easy:latest'
    restart: always
    ports:
      - '51820:51820/udp'
      - '51821:51821/tcp'
    environment:
      - PUID=1000
      - PGID=1000
      - WG_HOST=vpn.mydomain.com
      - PASSWORD=supersecurepassword
    volumes:
      - data:/etc/wireguard
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.rp_filter=2
```

If anyone else runs into this, feel free to drop the error you're getting here, I might have also encountered it and might remember what fixed it (no guarantees though).
