### ISSUE TITLE
No way to disable password

### ISSUE THREAD

**Issue by smshr** [WeeJeWel/wg-easy#5]
Is there any way to disable password prompt that comes at the start of ui? I looked for it in the source as well, but looks like it is mandatory for now.

I don't really need it as I use [authelia](https://github.com/authelia/authelia) with 2fa for authentication with traefik reverse-proxy.

**Comment by WeeJeWel** [comment]
Just don't set the `PASSWORD` environment variable.

**Comment by smshr** [comment]
@WeeJeWel: of-course! Silly how I missed it.

**Comment by stratosgear** [comment]
@smshr I just came here to see how I can configure wg-easy to run behind Traefik, and it seems that you are the only one here that you got it running.

I have something like:

```
version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=mydomain.com

      # Optional:
      - PASSWORD=somePasss
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1

    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /data/dockerfiles/wg-easy/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    labels:
      traefik.enable: 'true'
      traefik.http.routers.wireguard.entrypoints: websecure
      traefik.http.routers.wireguard.rule: Host(`vpn.mydomain.com`)
      traefik.http.routers.wireguard.tls.certresolver: letsencryptresolver
      traefik.http.services.wireguard.loadbalancer.server.port: '51821'
      traefik.udp.routers.wireguard.entrypoints: wireguard
      traefik.udp.services.wireguard.loadbalancer.server.port: '51820'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
```

but although I can hit the gui to create wg clients, my clients cannot connect.  I see that the wg handshake fails and the connection cannot be established.  This leads me to believe that traffic on 51820 does not reach the wg-easy  container.

Care to share your traefik configuration?  Are you with docker-compose too...?

Thanks!
